import os
import glob

configfile: "config.yaml"

SAMPLES = config["samples"]
GENOME_DIR = config["genome_dir"]
BUSCO_REF = config["busco_ref_dir"]
OUTDIR = config["outdir"]

rule all:
    input:
        expand(f"{OUTDIR}/fake_busco/{{sample}}/extract.done", sample=SAMPLES),
        f"{OUTDIR}/phylogenomics_done.txt"

# -------------------------------
rule concat_buscos:
# -------------------------------
    input:
        expand(f"{BUSCO_REF}/{{busco}}.faa",
               busco=[os.path.basename(f).replace(".faa", "") for f in glob.glob(f"{BUSCO_REF}/*.faa")])
    output:
        f"{OUTDIR}/all_buscos.faa"
    conda:
        "envs/python.yaml"
    shell:
        """
        cat {input} | awk '/^>/{{sub(/_.*/,"");}}1' > {output}
        """

# -------------------------------
rule miniprot:
# -------------------------------
    input:
        genome = f"{GENOME_DIR}/{{sample}}.fasta",
        buscos = f"{OUTDIR}/all_buscos.faa"
    output:
        gff = f"{OUTDIR}/miniprot/{{sample}}.gff"
    log:
        f"{OUTDIR}/logs/miniprot/{{sample}}.log"
    threads: config["miniprot_threads"]
    conda:
        "envs/miniprot.yaml"
    shell:
        """
        mkdir -p {OUTDIR}/logs/miniprot
        miniprot --gff-only -t {threads} {input.genome} {input.buscos} > {output.gff} 2> {log}
        """

# -------------------------------
rule extract_buscos:
# -------------------------------
    input:
        gff = f"{OUTDIR}/miniprot/{{sample}}.gff",
        genome = f"{GENOME_DIR}/{{sample}}.fasta"
    output:
        buscodir = directory(f"{OUTDIR}/fake_busco/{{sample}}/run_aspergillus_odb12/busco_sequences/single_copy_busco_sequences"),
        done = f"{OUTDIR}/fake_busco/{{sample}}/extract.done"
    conda:
        "envs/gffread.yaml"
    shell:
        """
        mkdir -p {output.buscodir}
        # Extract all CDS as protein sequences
        gffread -g {input.genome} -F -E -C -V -J -y {output.buscodir}/all_buscos.faa {input.gff}
        touch {output.done}
        """
# -------------------------------
rule run_phylogenomics:
# -------------------------------
    input:
        expand(f"{OUTDIR}/fake_busco/{{sample}}/extract.done", sample=SAMPLES)
    output:
        f"{OUTDIR}/phylogenomics_done.txt"
    log:
        f"{OUTDIR}/logs/phylogenomics.log"
    threads: config["threads"]
    conda:
        "envs/BUSCO_phylogenomics.yaml"
    shell:
        """
        mkdir -p {OUTDIR}/logs

        python BUSCO_phylogenomics.py \
            -i {OUTDIR}/fake_busco \
            -o {OUTDIR}/phylo \
            -t {threads} \
            --supermatrix_only \
            --supermatrix_iqtree \
            --filter_50 \
            --write_stats \
            > {log} 2>&1

        touch {output}
        """